CREATE DATABASE LEAVEMANAGE1;
USE LEAVEMANAGE1;

CREATE TABLE EMPLOGIN(
EMPID BIGINT(10),
EMPPASSWORD VARCHAR(100) NOT NULL,
enabled TINYINT NOT NULL DEFAULT 1 ,
PRIMARY KEY(EMPID));

CREATE TABLE user_roles (
  user_role_id int(11) NOT NULL AUTO_INCREMENT,
  EMPID BIGINT(10),
  role varchar(45) NOT NULL,
  PRIMARY KEY (user_role_id),
  UNIQUE KEY uni_EMPID_role (role,EMPID),
  KEY fk_username_idx (EMPID),
  CONSTRAINT fk_EMPID FOREIGN KEY (EMPID) REFERENCES EMPLOGIN (EMPID));


INSERT INTO emplogin(empid,emppassword,enabled)
VALUES (1234,'123456', true);
INSERT INTO emplogin(empid,emppassword,enabled)
VALUES (123,'123456', true);

INSERT INTO user_roles (empid, role)
VALUES (1234, 'ROLE_USER');
INSERT INTO user_roles (empid, role)
VALUES (1234, 'ROLE_ADMIN');
INSERT INTO user_roles (empid, role)
VALUES (123, 'ROLE_USER');

CREATE TABLE EMPDETAILS(EMPID BIGINT(10),
EMPNAME VARCHAR(50),
DATEOFJOINING DATE,
BLOODGRP VARCHAR(10),
GENDER VARCHAR(6),
PLANEDLEAVES DOUBLE(4,2),
UNPLANEDLEAVES DOUBLE(4,2),
EMPMAIL VARCHAR(30),
PRIMARY KEY(EMPMAIL),
CONSTRAINT FK_DETAILS FOREIGN KEY(EMPID) 
REFERENCES EMPLOGIN (EMPID));

CREATE TABLE EMPLEAVE(
EMPID BIGINT(10),
TYPEOFLEAVE VARCHAR(20),
STARTDATE DATE,
ENDDATE DATE,
FIRSTHALF INT(4),
SECONDHALF INT(4),
STATUS VARCHAR(20),
REASON VARCHAR(50),
PRIMARY KEY (EMPID,STARTDATE) 
);

CREATE TABLE MANAGERLOGIN(
MANAGERID BIGINT(10),
MANAGERPASSWORD VARCHAR(100),
PRIMARY KEY (MANAGERID)
);

CREATE TABLE MANAGERLEAVE(
 LEAVENUM INT(4) NOT NULL AUTO_INCREMENT,
 EMPID BIGINT(10),
 STATUS VARCHAR(20),
 PRIMARY KEY (LEAVENUM)
 );